name: Compile Kernel MT6771

on:
  workflow_dispatch:
jobs:
  Kernel:
    env:
        GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      checks: read
    steps:
      - uses: actions/checkout@v7
      
      - name: Setup SWAP
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16
          
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
          libssl-dev \
          libelf-dev \
          libdw-dev \
          build-essential \
          dwarves \
          gcc-aarch64-linux-gnu \
          linux-tools-common 
          
      - name: Clone Kernel Source
        run: |
          git clone https://github.com/oppo-source/android_kernel_oppo_mt6771.git --depth=1 mt6771
          git clone https://github.com/oppo-source/android_kernel_modules_oppo_mt6771.git --depth=1 mt6771-modules
          cp ${GITHUB_WORKSPACE}/mt6771-modules/source/vendor ${GITHUB_WORKSPACE}/ 
      - name: Download AOSP Clang
        run: |
              curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android10-release/clang-r353983b.tar.gz
              
              curl -LO https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/heads/android10-release.tar.gz
              
              mkdir -p toolchains/clang-r353983b
              mkdir -p toolchains/gcc
              
              tar -xf "clang-r353983b.tar.gz" -C "toolchains/clang-r353983b"
              tar -xf "android10-release.tar.gz" -C "toolchains/gcc"
              
      - name: Make Config & Build Kernel Image
        run: |
          export PATH="${GITHUB_WORKSPACE}/toolchains/clang-r353983b/bin:$PATH"
          export PATH="${GITHUB_WORKSPACE}/toolchains/gcc/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export LLVM=1
          export LLVM_IAS=0
          export CROSS_COMPILE=aarch64-linux-gnu-
          export KBUILD_BUILD_USER="twkp" 
          export KBUILD_BUILD_HOST="liuweien339-sys"
          
          cd mt6771
          make oppo6771_defconfig
          
          make -j$(nproc) Image 2>&1 | tee ${GITHUB_WORKSPACE}/build.log

      - name: Make AnyKernel3
        run: |
          ZIP_NAME="kernel"
          git clone https://github.com/liuweien339-sys/AnyKernel3.git ak3
          cp mt6878/arch/arm64/boot/Image ak3/
          cp build.log ak3/
          cd ak3 

          zip -r9 ../"${ZIP_NAME}.zip" * -x .git

      - name: Upload to GitHub Actions Artifacts
        uses: actions/upload-artifact@v7
        with:
         name: MT6771Kernel
         path: |
          ak3/*
         if-no-files-found: error
         compression-level: 6
